In [116]:
import pandas as pd

In [140]:
df = pd.read_csv('Car Dataset Processed.csv')

In [141]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [142]:
df['insurance_validity'].value_counts()

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [143]:
df['insurance_validity'] = df['insurance_validity'].map({'Comprehensive': 0, 'Third Party insurance': 1, 'Zero Dep': 2, 'Not Available': 3, 'Third Party':1})

In [144]:
df['insurance_validity'].value_counts()

insurance_validity
0    1081
1     352
2      64
3       2
Name: count, dtype: int64

In [145]:
df.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

In [146]:
df['fuel_type'].value_counts()

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

In [147]:
df['fuel_type'] = df['fuel_type'].map({'Petrol': 0, 'Diesel': 1, 'CNG': 2, 'LPG': 3})

In [148]:
df['fuel_type'].value_counts()

fuel_type
0    997
1    480
2     22
Name: count, dtype: int64

In [149]:
df.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

In [150]:
df['ownsership'].value_counts()

ownsership
First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: count, dtype: int64

In [151]:
df['ownsership'] = df['ownsership'].map({'First Owner': 0, 'Second Owner': 1, 'Third Owner': 2, 'Fourth Owner':3,'Fifth Owner':4})

In [152]:
df['ownsership'].value_counts()

ownsership
0    1236
1     240
2      21
4       2
Name: count, dtype: int64

In [153]:
df.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

In [154]:
df['transmission'].value_counts()

transmission
Manual       832
Automatic    667
Name: count, dtype: int64

In [155]:
df['transmission'] = df['transmission'].map({'Manual': 0, 'Automatic': 1})

In [156]:
df['transmission'].value_counts()

transmission
0    832
1    667
Name: count, dtype: int64

In [157]:
df.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

In [158]:
df['registration_year']

0       Jul-17
1       Jan-21
2       Sep-18
3       Dec-19
4       Aug-19
         ...
1494    May-22
1495    Aug-20
1496    Jun-17
1497    May-18
1498    May-18
Name: registration_year, Length: 1499, dtype: object

In [165]:
X = df[['insurance_validity', 'fuel_type', 'kms_driven', 'ownsership', 'transmission']]
y = df['price(in lakhs)']

In [166]:
X.head()

   insurance_validity  fuel_type  kms_driven  ownsership  transmission
0                   0          0       56000           0             1
1                   0          0       30615           0             1
2                   0          1       24000           0             1
3                   0          0       18378           0             0
4                   0          0       44900           0             1

In [167]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [168]:
models = {'LinReg':LinearRegression(),
          'KNN-3':KNeighborsRegressor(n_neighbors=3),
          'SVM-Polly':SVR(kernel='poly')}

for name,model in models.items():
    model.fit(X,y)
    sc = model.score(X,y)
    print(name,sc)

LinReg 0.01881841973825704
KNN-3 0.5927605118086187
SVM-Polly -0.002159341305929763

In [170]:
final_model = models['KNN-3']

In [173]:
d1={'Comprehensive': 0,'Third Party insurance': 1,'Zero Dep': 2,'Not Available': 3,'Third Party': 1}
d2={'Petrol': 0, 'Diesel': 1, 'CNG': 2}
d3={'Manual': 0, 'Automatic': 1}
d4={'First Owner': 1,'Second Owner': 2,'Third Owner': 3,'Fifth Owner': 5,'Fourth Owner': 4}

In [174]:
insurance_validity = input('Insurance validity: ')
fuel_type = input('Fuel Type: ')
kms_driven = input('KMs Driven: ')
ownsership = input('Ownership: ')
transmission = input('Transmission Type: ')
insurance_validity = d1[insurance_validity]
fuel_type = d2[fuel_type]
transmission = d3[transmission]
ownsership = d4[ownsership]
kms_driven = int(kms_driven)
test = [[insurance_validity,fuel_type,kms_driven,ownsership,transmission]]
yp = int(final_model.predict(test)[0])
print('Predicted Car Price is {} Rs.'.format(yp))

Insurance validity:  Zero Dep
Fuel Type:  Diesel
KMs Driven:  200000
Ownership:  Second Owner
Transmission Type:  Automatic

Predicted Car Price is 13 Rs.

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [175]:
import pickle
pickle.dump(final_model,open('final_model.pkl','wb'))